main: fr.xamez.cite_quests.CiteQuests
name: Cite-quests
version: 1.0
author: Xamez
api-version: 1.16
depend:
  - Cite-quest-core
commands:
  quest:
    description: Ouvre l'interface des qûetes
    aliases: [q, quete]
  tcc: